"""Initial schema

Revision ID: 44b52e61b180
Revises:
Create Date: 2026-07-19 14:51:43.742434

The original autogenerated body of this revision only altered one column, so `alembic upgrade head`
failed on an empty database (this project had always provisioned tables with `create_all` at API
startup). It now creates every table that does not exist yet - a no-op on a database that already
has them - so the history runs from empty to current on both a new and an existing database.
"""

from alembic import op
from sqlalchemy import text

from packages.domain import models  # noqa: F401 - registers every model on Base.metadata
from packages.infrastructure.database.base import Base

revision = "44b52e61b180"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    bind.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
    Base.metadata.create_all(bind=bind, checkfirst=True)


def downgrade() -> None:
    # Dropping every table is never what a rollback of the baseline should do silently.
    raise NotImplementedError("The baseline revision cannot be downgraded.")
