"""Initial schema

Revision ID: 44b52e61b180
Revises: 
Create Date: 2026-07-19 14:51:43.742434
"""

from alembic import op
import sqlalchemy as sa




revision = '44b52e61b180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_profiles', 'embedding_dimensions',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_profiles', 'embedding_dimensions',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###